# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LYModuleDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LYModuleDemo
  pod 'AFNetworking', '~> 3.2.1'
  pod 'SDWebImage', '~> 5.1.0'
  pod 'Masonry', '~> 1.1.0'

end

